[versions]
ktor = "3.4.2"

[libraries]
bom = {group = "io.ktor", name = "ktor-bom", version.ref = "ktor" }
callId = {group = "io.ktor", name = "ktor-call-id", version.ref = "ktor" }
client-android = {group = "io.ktor", name = "ktor-client-android", version.ref = "ktor" }
client-apache = {group = "io.ktor", name = "ktor-client-apache", version.ref = "ktor" }
client-apache5 = {group = "io.ktor", name = "ktor-client-apache5", version.ref = "ktor" }
client-auth = {group = "io.ktor", name = "ktor-client-auth", version.ref = "ktor" }
client-bomRemover = {group = "io.ktor", name = "ktor-client-bom-remover", version.ref = "ktor" }
client-callId = {group = "io.ktor", name = "ktor-client-call-id", version.ref = "ktor" }
client-cio = {group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
client-contentNegotiation = {group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
client-core = {group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
client-curl = {group = "io.ktor", name = "ktor-client-curl", version.ref = "ktor" }
client-darwin = {group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }
client-darwin-legacy = {group = "io.ktor", name = "ktor-client-darwin-legacy", version.ref = "ktor" }
client-encoding = {group = "io.ktor", name = "ktor-client-encoding", version.ref = "ktor" }
client-gson = {group = "io.ktor", name = "ktor-client-gson", version.ref = "ktor" }
client-ios = {group = "io.ktor", name = "ktor-client-ios", version.ref = "ktor" }
client-jackson = {group = "io.ktor", name = "ktor-client-jackson", version.ref = "ktor" }
client-java = {group = "io.ktor", name = "ktor-client-java", version.ref = "ktor" }
client-jetty = {group = "io.ktor", name = "ktor-client-jetty-jakarta", version.ref = "ktor" }
client-jetty-legacy = {group = "io.ktor", name = "ktor-client-jetty", version.ref = "ktor" }
client-js = {group = "io.ktor", name = "ktor-client-js", version.ref = "ktor" }
client-json = {group = "io.ktor", name = "ktor-client-json", version.ref = "ktor" }
client-logging = {group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
client-mock = {group = "io.ktor", name = "ktor-client-mock", version.ref = "ktor" }
client-okhttp = {group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
client-resources = {group = "io.ktor", name = "ktor-client-resources", version.ref = "ktor" }
client-serialization = {group = "io.ktor", name = "ktor-client-serialization", version.ref = "ktor" }
client-webrtc = {group = "io.ktor", name = "ktor-client-webrtc", version.ref = "ktor" }
client-websockets = {group = "io.ktor", name = "ktor-client-websockets", version.ref = "ktor" }
client-winhttp = {group = "io.ktor", name = "ktor-client-winhttp", version.ref = "ktor" }
encodingZstd = {group = "io.ktor", name = "ktor-encoding-zstd", version.ref = "ktor" }
events = {group = "io.ktor", name = "ktor-events", version.ref = "ktor" }
gradlePlugin = {group = "io.ktor.plugin", name = "plugin", version.ref = "ktor" }
htmx = {group = "io.ktor", name = "ktor-htmx", version.ref = "ktor" }
htmx-html = {group = "io.ktor", name = "ktor-htmx-html", version.ref = "ktor" }
http = {group = "io.ktor", name = "ktor-http", version.ref = "ktor" }
http-cio = {group = "io.ktor", name = "ktor-http-cio", version.ref = "ktor" }
io = {group = "io.ktor", name = "ktor-io", version.ref = "ktor" }
network = {group = "io.ktor", name = "ktor-network", version.ref = "ktor" }
network-tls = {group = "io.ktor", name = "ktor-network-tls", version.ref = "ktor" }
network-tls-certificates = {group = "io.ktor", name = "ktor-network-tls-certificates", version.ref = "ktor" }
openapiSchema = {group = "io.ktor", name = "ktor-openapi-schema", version.ref = "ktor" }
openapiSchema-reflect = {group = "io.ktor", name = "ktor-openapi-schema-reflect", version.ref = "ktor" }
resources = {group = "io.ktor", name = "ktor-resources", version.ref = "ktor" }
serialization = {group = "io.ktor", name = "ktor-serialization", version.ref = "ktor" }
serialization-gson = {group = "io.ktor", name = "ktor-serialization-gson", version.ref = "ktor" }
serialization-jackson = {group = "io.ktor", name = "ktor-serialization-jackson", version.ref = "ktor" }
serialization-jackson3 = {group = "io.ktor", name = "ktor-serialization-jackson3", version.ref = "ktor" }
serialization-kotlinx = {group = "io.ktor", name = "ktor-serialization-kotlinx", version.ref = "ktor" }
serialization-kotlinx-cbor = {group = "io.ktor", name = "ktor-serialization-kotlinx-cbor", version.ref = "ktor" }
serialization-kotlinx-json = {group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
serialization-kotlinx-protobuf = {group = "io.ktor", name = "ktor-serialization-kotlinx-protobuf", version.ref = "ktor" }
serialization-kotlinx-xml = {group = "io.ktor", name = "ktor-serialization-kotlinx-xml", version.ref = "ktor" }
server-auth = {group = "io.ktor", name = "ktor-server-auth", version.ref = "ktor" }
server-auth-apiKey = {group = "io.ktor", name = "ktor-server-auth-api-key", version.ref = "ktor" }
server-auth-jwt = {group = "io.ktor", name = "ktor-server-auth-jwt", version.ref = "ktor" }
server-auth-ldap = {group = "io.ktor", name = "ktor-server-auth-ldap", version.ref = "ktor" }
server-autoHeadResponse = {group = "io.ktor", name = "ktor-server-auto-head-response", version.ref = "ktor" }
server-bodyLimit = {group = "io.ktor", name = "ktor-server-body-limit", version.ref = "ktor" }
server-cachingHeaders = {group = "io.ktor", name = "ktor-server-caching-headers", version.ref = "ktor" }
server-callId = {group = "io.ktor", name = "ktor-server-call-id", version.ref = "ktor" }
server-callLogging = {group = "io.ktor", name = "ktor-server-call-logging", version.ref = "ktor" }
server-cio = {group = "io.ktor", name = "ktor-server-cio", version.ref = "ktor" }
server-compression = {group = "io.ktor", name = "ktor-server-compression", version.ref = "ktor" }
server-compression-zstd = {group = "io.ktor", name = "ktor-server-compression-zstd", version.ref = "ktor" }
server-conditionalHeaders = {group = "io.ktor", name = "ktor-server-conditional-headers", version.ref = "ktor" }
server-config-yaml = {group = "io.ktor", name = "ktor-server-config-yaml", version.ref = "ktor" }
server-contentNegotiation = {group = "io.ktor", name = "ktor-server-content-negotiation", version.ref = "ktor" }
server-core = {group = "io.ktor", name = "ktor-server-core", version.ref = "ktor" }
server-cors = {group = "io.ktor", name = "ktor-server-cors", version.ref = "ktor" }
server-csrf = {group = "io.ktor", name = "ktor-server-csrf", version.ref = "ktor" }
server-dataConversion = {group = "io.ktor", name = "ktor-server-data-conversion", version.ref = "ktor" }
server-defaultHeaders = {group = "io.ktor", name = "ktor-server-default-headers", version.ref = "ktor" }
server-di = {group = "io.ktor", name = "ktor-server-di", version.ref = "ktor" }
server-doubleReceive = {group = "io.ktor", name = "ktor-server-double-receive", version.ref = "ktor" }
server-forwardedHeader = {group = "io.ktor", name = "ktor-server-forwarded-header", version.ref = "ktor" }
server-freemarker = {group = "io.ktor", name = "ktor-server-freemarker", version.ref = "ktor" }
server-hsts = {group = "io.ktor", name = "ktor-server-hsts", version.ref = "ktor" }
server-htmlBuilder = {group = "io.ktor", name = "ktor-server-html-builder", version.ref = "ktor" }
server-htmx = {group = "io.ktor", name = "ktor-server-htmx", version.ref = "ktor" }
server-httpRedirect = {group = "io.ktor", name = "ktor-server-http-redirect", version.ref = "ktor" }
server-i18n = {group = "io.ktor", name = "ktor-server-i18n", version.ref = "ktor" }
server-jetty = {group = "io.ktor", name = "ktor-server-jetty-jakarta", version.ref = "ktor" }
server-jetty-legacy = {group = "io.ktor", name = "ktor-server-jetty", version.ref = "ktor" }
server-jte = {group = "io.ktor", name = "ktor-server-jte", version.ref = "ktor" }
server-methodOverride = {group = "io.ktor", name = "ktor-server-method-override", version.ref = "ktor" }
server-metrics = {group = "io.ktor", name = "ktor-server-metrics", version.ref = "ktor" }
server-metrics-micrometer = {group = "io.ktor", name = "ktor-server-metrics-micrometer", version.ref = "ktor" }
server-mustache = {group = "io.ktor", name = "ktor-server-mustache", version.ref = "ktor" }
server-netty = {group = "io.ktor", name = "ktor-server-netty", version.ref = "ktor" }
server-openapi = {group = "io.ktor", name = "ktor-server-openapi", version.ref = "ktor" }
server-partialContent = {group = "io.ktor", name = "ktor-server-partial-content", version.ref = "ktor" }
server-pebble = {group = "io.ktor", name = "ktor-server-pebble", version.ref = "ktor" }
server-rateLimit = {group = "io.ktor", name = "ktor-server-rate-limit", version.ref = "ktor" }
server-requestValidation = {group = "io.ktor", name = "ktor-server-request-validation", version.ref = "ktor" }
server-resources = {group = "io.ktor", name = "ktor-server-resources", version.ref = "ktor" }
server-routingOpenapi = {group = "io.ktor", name = "ktor-server-routing-openapi", version.ref = "ktor" }
server-servlet = {group = "io.ktor", name = "ktor-server-servlet-jakarta", version.ref = "ktor" }
server-servlet-legacy = {group = "io.ktor", name = "ktor-server-servlet", version.ref = "ktor" }
server-sessions = {group = "io.ktor", name = "ktor-server-sessions", version.ref = "ktor" }
server-sse = {group = "io.ktor", name = "ktor-server-sse", version.ref = "ktor" }
server-statusPages = {group = "io.ktor", name = "ktor-server-status-pages", version.ref = "ktor" }
server-swagger = {group = "io.ktor", name = "ktor-server-swagger", version.ref = "ktor" }
server-testHost = {group = "io.ktor", name = "ktor-server-test-host", version.ref = "ktor" }
server-thymeleaf = {group = "io.ktor", name = "ktor-server-thymeleaf", version.ref = "ktor" }
server-tomcat = {group = "io.ktor", name = "ktor-server-tomcat-jakarta", version.ref = "ktor" }
server-tomcat-legacy = {group = "io.ktor", name = "ktor-server-tomcat", version.ref = "ktor" }
server-velocity = {group = "io.ktor", name = "ktor-server-velocity", version.ref = "ktor" }
server-webjars = {group = "io.ktor", name = "ktor-server-webjars", version.ref = "ktor" }
server-websockets = {group = "io.ktor", name = "ktor-server-websockets", version.ref = "ktor" }
sse = {group = "io.ktor", name = "ktor-sse", version.ref = "ktor" }
testDispatcher = {group = "io.ktor", name = "ktor-test-dispatcher", version.ref = "ktor" }
utils = {group = "io.ktor", name = "ktor-utils", version.ref = "ktor" }
websockets = {group = "io.ktor", name = "ktor-websockets", version.ref = "ktor" }
websockets-serialization = {group = "io.ktor", name = "ktor-websocket-serialization", version.ref = "ktor" }

[plugins]
ktor = {id = "io.ktor.plugin", version.ref = "ktor" }

