#
# Copyright 2014-2026 JetBrains s.r.o and contributors. Use of this source code is governed by the Apache 2.0 license.
#

env.GRADLE_OPTS=-Dorg.gradle.internal.plugins.portal.url.override=https://cache-redirector.jetbrains.com/plugins.gradle.org/m2
env.MVNW_REPOURL=https://cache-redirector.jetbrains.com/repo.maven.apache.org/maven2
