[versions]
kaml-version = "0.56.0"
semver-version = "3.1.0"

[libraries]
kaml = { module = "com.charleskorn.kaml:kaml", version.ref = "kaml-version" }
semver = { module = "com.vdurmont:semver4j", version.ref = "semver-version" }