[versions]
kaml-version = "0.57.0"
maven-artifact-version = "3.9.6"

[libraries]
kaml = { module = "com.charleskorn.kaml:kaml", version.ref = "kaml-version" }
maven-artifact = { module = "org.apache.maven:maven-artifact", version.ref = "maven-artifact-version" }